export const schemaName = 'zhiyu';

export const migrationTables = [
  'users',
  'user_preferences',
  'user_devices',
  'user_sessions',
  'user_email_otp',
  'user_data_exports',
  'admin_users',
  'admin_audit_logs',
  'feature_flags',
  'admin_announcements',
  'content_review_workflow',
  'content_categories',
  'content_articles',
  'content_sentences',
  'content_tracks',
  'content_stages',
  'content_chapters',
  'content_lessons',
  'content_knowledge_points',
  'content_questions',
  'content_quizzes',
  'learning_reading_progress',
  'learning_progress',
  'learning_quiz_attempts',
  'learning_wrong_set',
  'learning_sessions',
  'user_track_enrollments',
  'user_stage_purchases',
  'course_content_reports',
  'course_import_jobs',
  'user_favorites',
  'user_notes',
  'content_ratings',
  'error_events',
  'events',
  'security_events',
  'blocked_entities',
  'red_line_dictionary',
  'coin_wallets',
  'coin_ledger',
  'export_jobs'
] as const;